
version: '3.8'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  web:
    build: .
    command: gunicorn drive.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db